---

- hosts: all
  become: true
  tasks:


 # - name: update repository index
 #  apt:
 #    update_cache: yes

  - name: install apache2 and php
    package: 
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"  
      state: latest  
      update_cache: yes  
